/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Utilities;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;

/**
 *
 * @author baj80000445
 */
public class GUI_Page1 extends javax.swing.JFrame implements ActionListener {

	/**
	 * 
	 */
	private static final long serialVersionUID = 990939798574163374L;
	private static String Browser;
	private static String Channel;
	private static String Environment;
	private static String Language;
	private static String Emails;

	/**
	 * Creates new form NewJFrame
	 */
	public GUI_Page1() {
		initComponents();
	}

	// Setters and getters
	public static String getjComboBoxBrowser() {
		return Browser;
	}

	public void setjComboBoxBrowser(String selectedBrowser) {
		GUI_Page1.Browser = selectedBrowser;
	}

	public static String getjComboBoxChannel() {
		return Channel;
	}

	public void setjComboBoxChannel(String selectedChannel) {
		GUI_Page1.Channel = selectedChannel;
	}

	// Setters and getters for Language
	public static String getjComboBoxEnvironment() {
		return Environment;
	}

	public void setjComboBoxEnvironment(String selectedEnvironment) {
		GUI_Page1.Environment = selectedEnvironment;
	}

	public static String getjComboBoxLanguage() {
		return Language;
	}

	public void setjComboBoxLanguage(String selectedLanguage) {
		GUI_Page1.Language = selectedLanguage;
	}

	public static String getTextFieldEmails() {
		return Emails;
	}

	public void setTextFieldEmails(String EnteredEmails) {
		GUI_Page1.Emails = EnteredEmails;
	}
	// End of Setters and getters
	// ########################################################

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		// creating objects and the design
		jComboBoxBrowser = new javax.swing.JComboBox<>();
		jComboBoxChannel = new javax.swing.JComboBox<>();
		jComboBoxEnvironment = new javax.swing.JComboBox<>();
		jComboBoxLanguage = new javax.swing.JComboBox<>();
		jtextEmail = new javax.swing.JTextArea();
		label2 = new javax.swing.JLabel();
		label3 = new javax.swing.JLabel();
		panel1 = new javax.swing.JPanel();
		label6 = new javax.swing.JLabel();
		label7 = new javax.swing.JLabel();
		label8 = new javax.swing.JLabel();
		button2 = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		button3 = new javax.swing.JButton();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jtextEmail.setText("Enter your E-mail (your E-mail@BAJ.COM.SA)");

		// To clear the text for the new Email upon clicking
		jtextEmail.addFocusListener(new FocusListener() {
			@Override
			public void focusGained(FocusEvent e) {
				jtextEmail.setText("");
			}

			@Override
			public void focusLost(FocusEvent e) {
				// TODO Auto-generated method stub

			}
		});

		label2.setText("Browser");
		label3.setText("Channel");
		javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
		panel1.setLayout(panel1Layout);
		panel1Layout.setHorizontalGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 0, Short.MAX_VALUE));
		panel1Layout.setVerticalGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 0, Short.MAX_VALUE));

		jComboBoxBrowser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Google Chrome", "Internet Explorer", "Firefox" }));
		jComboBoxBrowser.addActionListener(this);

		jComboBoxChannel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AlJazira Online", "AlJazira Smart", "AlJazira Corporate" }));
		jComboBoxChannel.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox2ActionPerformed(evt);
			}
		});

		jComboBoxChannel.addActionListener(this);
		jComboBoxEnvironment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UAT", "Pre-Production" }));
		jComboBoxEnvironment.addActionListener(this);
		jComboBoxLanguage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English", "Arabic" }));
		jComboBoxLanguage.addActionListener(this);

		label6.setText("Language");

		label7.setText("Environment");

		label8.setText("Email");

		button2.setLabel("Next >>");
		button2.setBackground(Color.GREEN);
		button2.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				button2ActionPerformed(evt);
			}
		}

		);

		button2.addActionListener(this);

		button3.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				button3ActionPerformed(evt);
			}
		}

		);
		System.out.println(System.getProperty("user.dir") + "\\bajSrcFiles\\resources\\extras\\BAJ.jpg");
		jLabel1.setIcon(new javax.swing.ImageIcon((System.getProperty("user.dir") + "\\bajSrcFiles\\resources\\extras\\BAJ.jpg"))); // NOI18N

		button3.setLabel("Exit");
		button3.setBackground(Color.RED);

		jMenu1.setText("BAJ");

		jMenuBar1.add(jMenu1);

		setJMenuBar(jMenuBar1);
		JMenuItem Items = new JMenuItem("About");
		jMenu1.add(Items);
		Items.addActionListener(this);
		Items.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				AboutActionPerformed(evt);
			}
		}

		);
		// Missing code to pop-up the About

		//

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout.createSequentialGroup()
										.addGroup(
												layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
														.addGroup(javax.swing.GroupLayout.Alignment.LEADING,
																layout.createSequentialGroup().addGap(40, 40, 40).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(layout.createSequentialGroup().addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																				.addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addGroup(javax.swing.GroupLayout.Alignment.LEADING,
																layout.createSequentialGroup().addGap(42, 42, 42)
																		.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup()
																				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
																				.addGap(20, 20, 20)
																				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
																						.addComponent(jComboBoxLanguage, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																						.addComponent(jComboBoxChannel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																						.addComponent(jComboBoxEnvironment, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																						.addComponent(jComboBoxBrowser, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
																				.addGroup(layout.createSequentialGroup().addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(20, 20, 20)
																						.addComponent(jtextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))))
										.addGap(0, 0, Short.MAX_VALUE))
						.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jLabel1).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(26, 26, 26).addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(47, 47, 47)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jComboBoxBrowser, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(33, 33, 33)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(label3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jComboBoxChannel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(33, 33, 33)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(label7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jComboBoxEnvironment, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(33, 33, 33)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(label6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jComboBoxLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(33, 33, 33)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(label8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jtextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										layout.createSequentialGroup().addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(33, 33, 33).addComponent(button3,
												javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addComponent(button2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(10, 10, 10)));

		pack();

		//// this is to add colour to the JFrame
		getContentPane().setBackground(new java.awt.Color(0, 102, 153));

		//// this is to add colour and the font to all labels
		label2.setFont(new Font("Calibri", Font.ITALIC, 16));
		label2.setForeground(Color.white);

		label3.setFont(new Font("Calibri", Font.ITALIC, 16));
		label3.setForeground(Color.white);

		label6.setFont(new Font("Calibri", Font.ITALIC, 16));
		label6.setForeground(Color.white);

		label7.setFont(new Font("Calibri", Font.ITALIC, 14));
		label7.setForeground(Color.white);

		label8.setFont(new Font("Calibri", Font.ITALIC, 16));
		label8.setForeground(Color.white);

		// this is to make the application on the middle and should be called after
		// pack() method otherwise it will not work
		setLocationRelativeTo(this);

	}// </editor-fold>

	private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void button2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		// to call Page#2

		GUI_Page2 m = new GUI_Page2();
		m.setVisible(true);
		setVisible(false); // to hide the log in frame

	}

	private void button3ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:

		// To Close the application when clicking on Exit button
		this.dispose();

	}

	private void AboutActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:

		// To Close the application when clicking on Exit button
		JOptionPane.showMessageDialog(this, "Version : 1.2.0.1 " + System.lineSeparator() + "For any support contact us via E-mail( UAT@BAJ.COM.SA )", "About this Application", JOptionPane.DEFAULT_OPTION);

	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf. html
		 */

		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(GUI_Page1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(GUI_Page1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(GUI_Page1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(GUI_Page1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */

		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				new GUI_Page1().setVisible(true);
			}
		});

	}

	// Variables declaration - do not modify
	private JButton button2;
	private JButton button3;
	private javax.swing.JComboBox<String> jComboBoxBrowser;
	private javax.swing.JComboBox<String> jComboBoxChannel;
	private javax.swing.JComboBox<String> jComboBoxEnvironment;
	private javax.swing.JComboBox<String> jComboBoxLanguage;
	private JLabel jLabel1;
	private JLabel label2;
	private JLabel label3;
	private JLabel label6;
	private JLabel label7;
	private JLabel label8;
	private JPanel panel1;
	private JTextArea jtextEmail;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenuBar jMenuBar1;
	// End of variables declaration

	@Override
	public void actionPerformed(ActionEvent actionEvent) {
		// TODO Auto-generated method stub

		String SelectedBrowser = (String) jComboBoxBrowser.getSelectedItem();
		setjComboBoxBrowser(SelectedBrowser);
		// System.out.println(SelectedChannel);

		// get Browser string
		String SelectedChannel = (String) jComboBoxChannel.getSelectedItem();
		setjComboBoxChannel(SelectedChannel);

		// get Test Type string
		String SelectedEnvironment = (String) jComboBoxEnvironment.getSelectedItem();
		setjComboBoxEnvironment(SelectedEnvironment);
		// System.out.println(SelectedTestType);

		// get Module string
		String SelectedLanguage = (String) jComboBoxLanguage.getSelectedItem();
		setjComboBoxLanguage(SelectedLanguage);

		String EnteredEmail = jtextEmail.getText();
		setTextFieldEmails(EnteredEmail);
		// setjComboBoxLanguage(SelectedLanguage);

	}

	public javax.swing.JMenu getjMenu2() {
		return jMenu2;
	}

	public void setjMenu2(javax.swing.JMenu jMenu2) {
		this.jMenu2 = jMenu2;
	}

}
